Repository Xithrius/twitch-tui, pull requests merged in 2021-09, with the labels that each got.

#7 Text wrapping
  Cargo.lock
  Cargo.toml
  src/handlers/data.rs
  src/tui.rs
Labels: enhancement, dependencies, size/M

#10 Adding colors to usernames.
  src/handlers/data.rs
  src/tui.rs
Labels: enhancement, size/S

#8 Unit testing
  src/handlers/data.rs
Labels: documentation, enhancement, size/M

#11 Improve error handling.
  src/main.rs
Labels: enhancement, size/S

#12 Improve username colors.
  default-config.toml
  src/handlers/config.rs
  src/handlers/data.rs
  src/tui.rs
Labels: enhancement, size/M

#13 General QOL features
  Cargo.lock
  Cargo.toml
  default-config.toml
  src/handlers/config.rs
  src/handlers/data.rs
  src/main.rs
  src/tui.rs
  src/twitch.rs
  src/utils/app.rs
  src/utils/mod.rs
  src/utils/text.rs
Labels: documentation, enhancement, dependencies, size/L

#14 A helpful popup window for keybinds.
  default-config.toml
  src/handlers/config.rs
  src/handlers/data.rs
  src/handlers/mod.rs
  src/main.rs
  src/terminal.rs
  src/tui.rs
  src/twitch.rs
  src/ui/chat.rs
  src/ui/keybinds.rs
  src/ui/mod.rs
  src/utils/app.rs
  src/utils/colors.rs
  src/utils/event.rs
  src/utils/mod.rs
  src/utils/text.rs
Labels: enhancement, size/XL

#17 Sending messages to Twitch chat from the terminal.
  default-config.toml
  src/handlers/config.rs
  src/main.rs
  src/terminal.rs
  src/twitch.rs
  src/ui/chat.rs
  src/utils/app.rs
  src/utils/event.rs
Labels: enhancement, size/L

#20 Possible fix for chat freezing
  src/terminal.rs
  src/twitch.rs
  src/utils/event.rs
Labels: bug, help wanted, size/M

#21 A small portion of unit testing
  src/handlers/data.rs
  src/terminal.rs
  src/utils/text.rs
Labels: documentation, enhancement, size/M

#22 Popup insert mode at the bottom of the terminal
  default-config.toml
  src/handlers/config.rs
  src/terminal.rs
  src/ui/chat.rs
  src/ui/keybinds.rs
  src/utils/text.rs
Labels: enhancement, size/M

#23 Improve performance.
  src/main.rs
  src/terminal.rs
  src/ui/chat.rs
  src/ui/keybinds.rs
  src/utils/text.rs
Labels: size/M

#24 Allowing this program to run on Windows.
  Cargo.lock
  Cargo.toml
  src/main.rs
  src/terminal.rs
  src/ui/chat.rs
  src/utils/event.rs
  src/utils/mod.rs
  src/utils/pathing.rs
Labels: enhancement, size/L
