Repository Xithrius/twitch-tui, pull requests merged in 2022-10, with the labels that each got.

#227 Clap 4.0
  .github/workflows/greetings.yml
  Cargo.lock
  Cargo.toml
  src/handlers/args.rs
  src/handlers/config.rs
  src/handlers/data.rs
  src/ui/mod.rs
  src/utils/text.rs
Labels: size/L

#230 Add result count to fuzzy search box.
  src/handlers/data.rs
  src/ui/mod.rs
Labels: size/S, hacktoberfest-accepted, area: frontend

#240 Environment variable support for tokens.
  book/src/README.md
  book/src/guide/README.md
  book/src/guide/configuration.md
  book/src/guide/installation.md
  src/handlers/config.rs
  src/twitch/connection.rs
Labels: area: documentation, size/M, area: backend
