Repository Xithrius/twitch-tui, pull requests merged in 2022-02, with the labels that each got.

#74 Preparing for v2.0
  .gitignore
  .vscode/launch.json
  .vscode/settings.json
  Cargo.lock
  Cargo.toml
  LICENSE
  src/handlers/app.rs
  src/handlers/data.rs
  src/main.rs
  src/terminal.rs
  src/twitch.rs
  src/ui/mod.rs
  src/ui/popups/channels.rs
  src/ui/popups/help.rs
  src/ui/popups/messages.rs
  src/ui/popups/mod.rs
Labels: type: enhancement, size/L, area: keybinds, area: frontend, area: backend

#107 Replacing StructOpt with Clap.
  Cargo.lock
  Cargo.toml
  src/handlers/args.rs
  src/main.rs
Labels: size/M

#108 Add twitch badges
  default-config.toml
  src/handlers/args.rs
  src/handlers/config.rs
  src/twitch.rs
  src/utils/text.rs
Labels: type: enhancement, size/M, area: frontend
