Repository Xithrius/twitch-tui, pull requests merged in 2023-08, with the labels that each got.

#438 Clearing and deleting messages
  src/handlers/app.rs
  src/handlers/data.rs
  src/terminal.rs
  src/twitch/connection.rs
  src/twitch/mod.rs
  src/ui/components/channel_switcher.rs
Labels: size/L

#440 Bump image-rs to 0.24.7
  Cargo.lock
  Cargo.toml
  src/emotes/graphics_protocol.rs
Labels: size/XS

#442 Clear a user's chat messages on timeout/ban
  src/handlers/app.rs
  src/handlers/data.rs
  src/terminal.rs
  src/twitch/mod.rs
  src/ui/components/chat.rs
Labels: size/L

#430 General search widget implementation
  Cargo.lock
  Cargo.toml
  src/emotes/downloader.rs
  src/emotes/graphics_protocol.rs
  src/emotes/mod.rs
  src/handlers/app.rs
  src/main.rs
  src/twitch/channels.rs
  src/twitch/mod.rs
  src/twitch/oauth.rs
  src/ui/components/channel_switcher.rs
  src/ui/components/chat.rs
  src/ui/components/chat_input.rs
  src/ui/components/dashboard.rs
  src/ui/components/debug.rs
  src/ui/components/error.rs
  src/ui/components/following.rs
  src/ui/components/help.rs
  src/ui/components/message_search.rs
  src/ui/components/mod.rs
  src/ui/components/utils/input_widget.rs
  src/ui/components/utils/mod.rs
  src/ui/components/utils/search_widget.rs
  src/utils/pathing.rs
Labels: size/XL
