Repository Xithrius/twitch-tui, pull requests merged in 2023-07, with the labels that each got.

#410 Add FrankerFacez emotes, refactor emotes downloader
  default-config.toml
  src/emotes/downloader.rs
  src/emotes/graphics_protocol.rs
  src/emotes/mod.rs
  src/handlers/config.rs
  src/main.rs
  src/terminal.rs
Labels: size/XL

#419 Managing/interacting with user's followers
  Cargo.lock
  Cargo.toml
  default-config.toml
  src/emotes/downloader.rs
  src/handlers/app.rs
  src/main.rs
  src/twitch/mod.rs
  src/twitch/oauth.rs
  src/ui/components/chat.rs
  src/ui/components/dashboard.rs
  src/ui/components/debug.rs
  src/ui/components/following.rs
  src/ui/components/mod.rs
  src/ui/components/utils/popups.rs
Labels: size/L

#423 Hotfix
  src/twitch/connection.rs
  src/twitch/oauth.rs
Labels: size/XS
