Repository Xithrius/twitch-tui, pull requests merged in 2023-04, with the labels that each got.

#317 Add support for displaying emotes using the terminal graphics protocol
  Cargo.lock
  Cargo.toml
  book/src/guide/configuration.md
  default-config.toml
  src/emotes/downloader.rs
  src/emotes/graphics_protocol.rs
  src/emotes/mod.rs
  src/handlers/config.rs
  src/handlers/data.rs
  src/handlers/user_input/input.rs
  src/main.rs
  src/terminal.rs
  src/twitch/mod.rs
  src/ui/mod.rs
  src/utils/pathing.rs
Labels: size/XXL

#339 Configure default channels in start screen.
  default-config.toml
  src/handlers/config.rs
  src/handlers/user_input/input.rs
  src/ui/components/dashboard/start.rs
Labels: type: enhancement, size/L, area: keybinds, area: frontend

#335 Add support for webp emotes
  Cargo.lock
  Cargo.toml
  src/emotes/downloader.rs
  src/emotes/graphics_protocol.rs
  src/emotes/mod.rs
  src/handlers/data.rs
Labels: size/XL

#351 Component rewrite.
  default-config.toml
  src/emotes/mod.rs
  src/handlers/app.rs
  src/handlers/args.rs
  src/handlers/config.rs
  src/handlers/mod.rs
  src/handlers/state.rs
  src/handlers/storage.rs
  src/handlers/user_input/events.rs
  src/handlers/user_input/input.rs
  src/handlers/user_input/mod.rs
  src/handlers/user_input/scrolling.rs
  src/main.rs
  src/terminal.rs
  src/ui/components/channel_switcher.rs
  src/ui/components/chatting.rs
  src/ui/components/chunks/chatting.rs
  src/ui/components/chunks/debug.rs
  src/ui/components/chunks/mod.rs
  src/ui/components/dashboard.rs
  src/ui/components/dashboard/mod.rs
  src/ui/components/dashboard/start.rs
  src/ui/components/debug.rs
  src/ui/components/error.rs
  src/ui/components/help.rs
  src/ui/components/mod.rs
  src/ui/components/popups/channels.rs
  src/ui/components/popups/mod.rs
  src/ui/components/state_tabs.rs
  src/ui/components/utils/insert_box.rs
  src/ui/components/utils/mod.rs
  src/ui/components/utils/popups.rs
  src/ui/error.rs
  src/ui/mod.rs
  src/ui/render.rs
  src/ui/statics.rs
Labels: type: enhancement, area: backend, size/XXL
