Repository Xithrius/twitch-tui, pull requests merged in 2024-05, with the labels that each got.

#595 Fix clippy lints introduced with rust 1.78
  src/handlers/config.rs
  src/handlers/state.rs
  src/handlers/storage.rs
  src/handlers/user_input/events.rs
  src/twitch/channels.rs
  src/ui/components/channel_switcher.rs
  src/ui/components/chat_input.rs
  src/ui/components/following.rs
  src/ui/components/message_search.rs
  src/ui/components/utils/input_widget.rs
Labels: size/L

#592 fix: ignored TWT_TOKEN env variable
  src/handlers/config.rs
Labels: type: bug, size/XS

#600 Add missing 'o' keybind
  book/src/keybinds/normal.md
Labels: size/XS
