Repository Xithrius/twitch-tui, pull requests merged in 2024-08, with the labels that each got.

#649 Fix off by one error in highlight
  Cargo.lock
  src/handlers/data.rs
Labels: size/S

#650 Fix off by one error in hightlight
  Cargo.lock
  src/handlers/data.rs
Labels: size/M

#651 Fixing Windows `winapi` crash on run with `SetUnderlineColor`
  Cargo.toml
  src/handlers/data.rs
  src/ui/components/emote_picker.rs
  src/utils/styles.rs
Labels: size/L
