Repository Xithrius/twitch-tui, pull requests merged in 2024-06, with the labels that each got.

#591 Correctly handle twitch subscriber emotes
  src/emotes/downloader.rs
  src/emotes/mod.rs
  src/handlers/data.rs
  src/terminal.rs
  src/twitch/channels.rs
  src/twitch/mod.rs
  src/twitch/oauth.rs
  src/ui/components/emote_picker.rs
  src/utils/text.rs
Labels: size/XL

#616 Correctly handle paginated response for twitch user emotes
  src/emotes/downloader.rs
Labels: size/M

#618 Change oauth config prefix in docs from `:oauth` to `oauth:`
  book/src/guide/configuration.md
Labels: size/XS

#619 add hide_chat_border to config
  default-config.toml
Labels: size/XS
