Repository Xithrius/twitch-tui, pull requests merged in 2025-07, with the labels that each got.

#682 remove config storage.channels check for autofill
  src/ui/components/utils/input_widget.rs
Labels: size/S

#681 fix grammar typo in follower command message
  src/twitch/mod.rs
Labels: size/XS

#683 add more websocket commands
  default-config.toml
  src/twitch/api/channel_information.rs
  src/twitch/api/chat_settings.rs
  src/twitch/api/commercial.rs
  src/twitch/api/mod.rs
  src/twitch/api/raids.rs
  src/twitch/api/shoutouts.rs
  src/twitch/commands.rs
  src/twitch/mod.rs
  src/ui/statics.rs
Labels: size/L

#688 Update dockerfile rust image
  .devcontainer/Dockerfile
Labels: size/XS
